tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"

brew "autoconf"
brew "automake"
brew "awscli"
brew "certbot"
brew "cfssl"
brew "dnsmasq", restart_service: true
brew "glib"
brew "gcc@5"
brew "git"
brew "libxml2"
brew "gettext"
brew "gnutls"
brew "gnupg"
brew "go"
brew "goenv"
brew "gpg2"
brew "hub"
brew "jpeg"
brew "jq"
brew "libevent"
brew "libffi"
brew "libmpc"
brew "libtool"
brew "libyaml"
brew "mas"
brew "nginx", restart_service: true
brew "node"
brew "node-build"
brew "nodenv"
brew "openssl"
brew "postgresql", restart_service: true
brew "redis", restart_service: true
brew "rbenv"
brew "ruby-build"
brew "s3cmd"
brew "siege"
brew "tig"
brew "wget"
brew "zsh"

cask "1password"
cask "dropbox"
cask "flux"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "postman"
cask "tableplus"
cask "visual-studio-code"
cask "zoomus"

mas "Numbers", id: 409203825
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
