#!/usr/local/bin/zsh

DOTFILES_DIR=$(cd "$(dirname $0)/.."; pwd)
cd $DOTFILES_DIR

source $DOTFILES_DIR/script/.shared
out "dotfiles/script/setup"

# Apply MacOS defaults
echo ""
run "sh $DOTFILES_DIR/macos/defaults.sh"

echo ""
symlink_dotfile Brewfile
symlink_dotfile railsrc
symlink_dotfile_force gitconfig
symlink_dotfile gitignore-global
symlink_dotfile_force zshrc
symlink_dotfile zsh
symlink_dotfile rbenv/default-gems
symlink_dotfile gemrc
symlink_dotfile editorconfig
symlink_dotfile eslintrc.json
symlink_dotfile gnupg/gpg.conf
symlink_dotfile gnupg/gpg-agent.conf

echo ""
symlink "$DOTFILES_DIR/vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
symlink "$DOTFILES_DIR/tslint.json" "$HOME/tslint.json"

# Permissions
chmod -R 700 ~/.gnupg
